language: java
sudo: false
script: 
  - cd lambdas/testFunction/ && mvn clean verify
  - cd ./../userLambdas/ && npm install && npm test && ./node_modules/.bin/eslint --fix UserLambda.js test/UserLambdaTest.js
